name: first_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  intl: ^0.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/waiting.png

  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Light.ttf
        - asset: assets/fonts/IBMPlexMono-LightItalic.ttf
          style: italic
        - asset: assets/fonts/IBMPlexMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
        - asset: assets/fonts/UbuntuMono-Bold.ttf
          weight: 700
